/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-12-22 15:56:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;
import java.sql.*;
import com.hotel.servlet.*;

public final class booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hotel.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLDecoder");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>酒店预订系统</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/hotelReservation/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/hotelReservation/css/booking.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav_main.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t");

		Integer hotelid =Integer.parseInt(request.getParameter("hotelid"));
		String name ="";
		Class.forName("com.mysql.jdbc.Driver");
		Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel?characterEncoding=utf-8&useSSL=false","root","123456");
		Statement stmtStatement = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
		String sqlString = "select ID,name,city,address,level,phone from hotel where ID = '"+hotelid+"'";
		ResultSet rs = stmtStatement.executeQuery(sqlString);
		while(rs.next())
		{
			name=rs.getString("name");
		}
		stmtStatement.close();
		connection.close();

      out.write("\r\n");
      out.write("\t\t<p id=\"bread\"><a href=\"/hotelReservation/jsp/main.jsp\" style=\"color: black;\">首页</a>-><a href=\"/hotelReservation/jsp/booking.jsp\" style=\"color: black;\">预订</a></p>\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t<form action=\"/hotelReservation/Booking\" method=\"post\" id=\"bookmsg\">\r\n");
      out.write("\t\t\t\t<p>酒店名称：<input type=\"hidden\" value=\"");
      out.print(name);
      out.write("\"  name=\"hotelname\">");
      out.print(name);
      out.write("</p>\r\n");
      out.write("\t\t\t\t<p>入住时间：<input type=\"date\" name=\"intime\"></p>\r\n");
      out.write("\t\t\t\t<p>退房时间：<input type=\"date\" name=\"outtime\"></p>\r\n");
      out.write("\t\t\t\t<p>身份证号：<input type=\"text\"\" name=\"idNum\"></p>\r\n");
      out.write("\t\t\t\t<p>房间类型：\r\n");
      out.write("\t\t\t\t\t<select name=\"roomType\">\r\n");
      out.write("\t\t\t\t\t\t<option>大床</option>\r\n");
      out.write("\t\t\t\t\t\t<option>双床</option>\r\n");
      out.write("\t\t\t\t\t\t<option>单人床</option>\r\n");
      out.write("\t\t\t\t\t\t<option>多床</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>房间数量：\r\n");
      out.write("\t\t\t\t\t<select name=\"roomNum\">\r\n");
      out.write("\t\t\t\t\t\t<option>1</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2</option>\r\n");
      out.write("\t\t\t\t\t\t<option>3</option>\r\n");
      out.write("\t\t\t\t\t\t<option>4</option>\r\n");
      out.write("\t\t\t\t\t\t<option>5</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t间\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>成人人数：\r\n");
      out.write("\t\t\t\t\t<select name=\"adultNum\">\r\n");
      out.write("\t\t\t\t\t\t<option>1</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2</option>\r\n");
      out.write("\t\t\t\t\t\t<option>3</option>\r\n");
      out.write("\t\t\t\t\t\t<option>4</option>\r\n");
      out.write("\t\t\t\t\t\t<option>5</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p>儿童人数：\r\n");
      out.write("\t\t\t\t\t<select name=\"childNum\">\r\n");
      out.write("\t\t\t\t\t\t<option>0</option>\r\n");
      out.write("\t\t\t\t\t\t<option>1</option>\r\n");
      out.write("\t\t\t\t\t\t<option>2</option>\r\n");
      out.write("\t\t\t\t\t\t<option>3</option>\r\n");
      out.write("\t\t\t\t\t\t<option>4</option>\r\n");
      out.write("\t\t\t\t\t\t<option>5</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" name=\"booking\" id=\"booking\" class=\"btn btn-success\" value=\"确认预订\">\r\n");
      out.write("\t\t\t\t<a href=\"/hotelReservation/jsp/main.jsp\" class=\"btn btn-danger\">取消预订</a>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
