/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-12-19 06:15:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>酒店预订系统---注册</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/hotelReservation/css/register.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/hotelReservation/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "register_head.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<form action=\"/hotelReservation/Register\" method=\"post\" id=\"register_form\">\r\n");
      out.write("\t\t\t<p><span style=\"color: red;\">*</span>手机号：<input type=\"text\" name=\"phone\" id=\"phone\" placeholder=\"有效手机号\" class=\"text\"><span id=\"id\"></span></p>\r\n");
      out.write("\t\t\t<p><span style=\"color: red;\">*</span>姓名：<input type=\"text\" name=\"username\" id=\"username\" class=\"text\"></p>\r\n");
      out.write("\t\t\t<p><span style=\"color: red;\">*</span>性别： <input type=\"radio\" name=\"sex\" value=\"男\">男<input type=\"radio\" name=\"sex\" value=\"女\">女</p>\r\n");
      out.write("\t\t\t<p><span style=\"color: red;\">*</span>身份证号：<input type=\"text\" name=\"idNum\" id=\"idNum\" class=\"text\"></p>\r\n");
      out.write("\t\t\t<p id=\"nick\">昵称：<input type=\"text\" name=\"nickname\" id=\"nickname\" class=\"text\"><span id=\"nickTip\"></span></p>\r\n");
      out.write("\t\t\t<p><span style=\"color: red;\">*</span>密码：<input type=\"password\" name=\"password\" id=\"password\" class=\"text\"><span id=\"pwd\"></span></p>\r\n");
      out.write("\t\t\t<p><span style=\"color: red;\">*</span>再次输入密码：<input type=\"password\" name=\"repwd\" id=\"repwd\" class=\"text\"><span id=\"rePwd\"></span></p>\r\n");
      out.write("\t\t\t<p class=\"write write5\"><span style=\"color: red;\">*</span>验证码：\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"check\" class=\"text\">\r\n");
      out.write("\t\t\t\t<img src=\"/hotelReservation/image/check1.png\" id=\"checkpic\">\r\n");
      out.write("\t\t\t\t<a href=\"\" id=\"change\">看不清楚？换张图片\t</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p id=\"checktip\" class=\"tip\">请填写图片中的字符，不区分大小写</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"agree\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"checkbox\" id=\"checkbox\" checked=\"checked\">\r\n");
      out.write("\t\t\t\t\t同意\"<span class=\"clause\">服务条款</span>\"和\"<span class=\"clause\">隐私权相关政策</span>\"\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"registerBtn\" name=\"register\" value=\"注册\" class=\"btn btn-primary btn-lg\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/hotelReservation/js/register.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
